### ISSUE TITLE
Broken Link for Fariz Rizaldy and Afwa Bagas Wahuda

### ISSUE THREAD

**Issue by jefrydco** [sutanlab/sutanlab.id#182]
I accessed link to Fariz Rizaldi and Afwa Bagas Wahuda on the following page, https://sutanlab.id/now. It seems they are broken link.

![jefrydco](https://user-images.githubusercontent.com/20434351/107876634-b0612280-6ef9-11eb-9d2c-ccce46ed7397.png)

**Comment by sutanlab** [comment]
Thanks for your report @jefrydco, i've updated broken link, maybe you can check it again to make sure the link work properly.
